/**
 * India destination aliases — single source of truth for server + mobile.
 * Maps alternate / historical / colloquial names → canonical keys used in place DB + geocode.
 */

export const INDIA_DESTINATION_ALIASES: Record<string, string> = {
  // Metros — historical / official renames
  bangalore: 'bengaluru',
  bengaluru: 'bengaluru',
  calcutta: 'kolkata',
  kolkata: 'kolkata',
  madras: 'chennai',
  chennai: 'chennai',
  bombay: 'mumbai',
  mumbai: 'mumbai',
  poona: 'pune',
  pune: 'pune',

  // Delhi NCR
  delhi: 'delhi',
  'new delhi': 'delhi',
  'old delhi': 'delhi',
  ncr: 'delhi',
  'delhi ncr': 'delhi',
  gurgaon: 'gurugram',
  gurugram: 'gurugram',

  // Uttar Pradesh / Bihar spiritual belt
  kashi: 'varanasi',
  banaras: 'varanasi',
  benares: 'varanasi',
  varanasi: 'varanasi',
  allahabad: 'prayagraj',
  prayagraj: 'prayagraj',
  ayodhya: 'ayodhya',
  mathura: 'mathura',
  vrindavan: 'vrindavan',
  agra: 'agra',
  lucknow: 'lucknow',
  sarnath: 'sarnath',
  'bodh gaya': 'bodh gaya',
  bodhgaya: 'bodh gaya',
  rajgir: 'rajgir',
  nalanda: 'nalanda',
  vaishali: 'vaishali',
  kushinagar: 'kushinagar',

  // Rajasthan
  jaipur: 'jaipur',
  udaipur: 'udaipur',
  jodhpur: 'jodhpur',
  jaisalmer: 'jaiselmer',
  bikaner: 'bikaner',
  pushkar: 'pushkar',
  'mount abu': 'mount abu',
  chittor: 'chittorgarh',
  chittaurgarh: 'chittorgarh',
  chittorgarh: 'chittorgarh',
  ranakpur: 'ranakpur',
  bundi: 'bundi',
  mandawa: 'mandawa',
  ranthambore: 'sawai madhopur',
  ranthambhore: 'sawai madhopur',
  'sawai madhopur': 'sawai madhopur',

  // Madhya Pradesh / Chhattisgarh
  bhopal: 'bhopal',
  indore: 'indore',
  jabalpur: 'jabalpur',
  ujjain: 'ujjain',
  gwalior: 'gwalior',
  khajuraho: 'khajuraho',
  orchha: 'orchha',
  sanchi: 'sanchi',
  pachmarhi: 'pachmarhi',
  mandu: 'mandu',
  kanha: 'kanha',
  bandhavgarh: 'bandhavgarh',
  pench: 'pench',
  amarkantak: 'amarkantak',
  burhanpur: 'burhanpur',
  maheshwar: 'maheshwar',
  chitrakoot: 'chitrakoot',
  datia: 'datia',
  shivpuri: 'shivpuri',

  // Maharashtra / Goa
  goa: 'goa',
  panaji: 'goa',
  panjim: 'goa',
  'north goa': 'goa',
  'south goa': 'goa',
  lonavala: 'lonavala',
  lonavla: 'lonavala',
  mahabaleshwar: 'mahabaleshwar',
  matheran: 'matheran',
  aurangabad: 'aurangabad',
  ajanta: 'ajanta',
  ellora: 'ellora',
  nashik: 'nashik',
  nasik: 'nashik',
  kolhapur: 'kolhapur',
  shirdi: 'shirdi',
  alibaug: 'alibaug',
  alibag: 'alibaug',
  tarkarli: 'tarkarli',

  // Karnataka
  mysore: 'mysuru',
  mysuru: 'mysuru',
  mangalore: 'mangaluru',
  mangaluru: 'mangaluru',
  belgaum: 'belagavi',
  belagavi: 'belagavi',
  hubli: 'hubballi',
  hubballi: 'hubballi',
  coorg: 'madikeri',
  kodagu: 'madikeri',
  madikeri: 'madikeri',
  hampi: 'hampi',
  gokarna: 'gokarna',
  chikmagalur: 'chikmagalur',
  chikkamagaluru: 'chikmagalur',
  badami: 'badami',
  shimoga: 'shivamogga',
  shivamogga: 'shivamogga',
  udupi: 'udupi',
  dandeli: 'dandeli',

  // Tamil Nadu / Puducherry
  ooty: 'ooty',
  udhagamandalam: 'ooty',
  udhagai: 'ooty',
  kodaikanal: 'kodaikanal',
  madurai: 'madurai',
  tiruchirappalli: 'tiruchirappalli',
  trichy: 'tiruchirappalli',
  tiruchy: 'tiruchirappalli',
  thanjavur: 'thanjavur',
  tanjore: 'thanjavur',
  tanjavur: 'thanjavur',
  tirupati: 'tirupati',
  tirumala: 'tirupati',
  kanyakumari: 'kanyakumari',
  'cape comorin': 'kanyakumari',
  rameswaram: 'rameswaram',
  rameshwaram: 'rameswaram',
  kanchipuram: 'kanchipuram',
  mahabalipuram: 'mahabalipuram',
  mamallapuram: 'mahabalipuram',
  pondicherry: 'puducherry',
  puducherry: 'puducherry',
  auroville: 'auroville',
  chidambaram: 'chidambaram',
  kumbakonam: 'kumbakonam',
  yercaud: 'yercaud',
  coonoor: 'coonoor',
  nilgiris: 'nilgiris',

  // Kerala
  kochi: 'kochi',
  cochin: 'kochi',
  ernakulam: 'kochi',
  'fort kochi': 'kochi',
  trivandrum: 'thiruvananthapuram',
  thiruvananthapuram: 'thiruvananthapuram',
  alleppey: 'alappuzha',
  alappuzha: 'alappuzha',
  calicut: 'kozhikode',
  kozhikode: 'kozhikode',
  munnar: 'munnar',
  thekkady: 'thekkady',
  kumarakom: 'kumarakom',
  varkala: 'varkala',
  kovalam: 'kovalam',
  wayanad: 'wayanad',
  kasaragod: 'kasaragod',
  thrissur: 'thrissur',
  guruvayur: 'guruvayur',

  // Andhra Pradesh / Telangana
  hyderabad: 'hyderabad',
  secunderabad: 'hyderabad',
  cyberabad: 'hyderabad',
  warangal: 'warangal',
  visakhapatnam: 'visakhapatnam',
  vizag: 'visakhapatnam',
  waltair: 'visakhapatnam',
  vijayawada: 'vijayawada',
  bezawada: 'vijayawada',
  srikalahasti: 'srikalahasti',
  lepakshi: 'lepakshi',

  // Gujarat / Daman-Diu
  ahmedabad: 'ahmedabad',
  amdavad: 'ahmedabad',
  vadodara: 'vadodara',
  baroda: 'vadodara',
  surat: 'surat',
  rajkot: 'rajkot',
  bhuj: 'bhuj',
  kutch: 'kutch',
  'rann of kutch': 'kutch',
  dwarka: 'dwarka',
  somnath: 'somnath',
  junagadh: 'junagadh',
  gir: 'talala gir',
  'sasan gir': 'talala gir',
  'talala gir': 'talala gir',
  saputara: 'saputara',
  diu: 'diu',
  daman: 'daman',
  modhera: 'modhera',
  palitana: 'palitana',
  champaner: 'champaner',
  kevadia: 'kevadia',
  'statue of unity': 'kevadia',
  lothal: 'lothal',

  // Punjab / Haryana / Chandigarh
  amritsar: 'amritsar',
  chandigarh: 'chandigarh',
  patiala: 'patiala',
  'anandpur sahib': 'anandpur sahib',
  kurukshetra: 'kurukshetra',
  kurukschetra: 'kurukshetra',

  // Himachal Pradesh
  shimla: 'shimla',
  simla: 'shimla',
  manali: 'manali',
  dharamshala: 'dharamshala',
  dharamsala: 'dharamshala',
  mcleodganj: 'mc leod ganj',
  'mc leod ganj': 'mc leod ganj',
  mcledoganj: 'mc leod ganj',
  dalhousie: 'dalhousie',
  kasauli: 'kasauli',
  kasol: 'kasol',
  kullu: 'kullu',
  spiti: 'spiti',
  chitkul: 'chitkul',
  bir: 'bir',

  // Uttarakhand
  nainital: 'nainital',
  'naini tal': 'nainital',
  mussoorie: 'mussoorie',
  masuri: 'mussoorie',
  mussourie: 'mussoorie',
  dehradun: 'dehradun',
  haridwar: 'haridwar',
  hardwar: 'haridwar',
  rishikesh: 'rishikesh',
  risikesh: 'rishikesh',
  auli: 'auli',
  corbett: 'jim corbett',
  'jim corbett': 'jim corbett',
  kedarnath: 'kedarnath',
  badrinath: 'badrinath',
  gangotri: 'gangotri',
  yamunotri: 'yamunotri',
  chopta: 'chopta',
  lansdowne: 'lansdowne',
  ranikhet: 'ranikhet',
  almora: 'almora',
  kausani: 'kausani',
  joshimath: 'joshimath',
  'valley of flowers': 'valley of flowers',

  // Jammu & Kashmir / Ladakh
  srinagar: 'srinagar',
  kashmir: 'kashmir',
  gulmarg: 'gulmarg',
  pahalgam: 'pahalgam',
  sonamarg: 'sonamarg',
  sonmarg: 'sonamarg',
  leh: 'leh',
  ladakh: 'ladakh',
  nubra: 'nubra',
  kargil: 'kargil',
  jammu: 'jammu',
  katra: 'katra',
  'vaishno devi': 'katra',

  // West Bengal / Sikkim
  darjeeling: 'darjeeling',
  kalimpong: 'kalimpong',
  siliguri: 'siliguri',
  gangtok: 'gangtok',
  shantiniketan: 'shantiniketan',
  santiniketan: 'shantiniketan',
  sundarbans: 'sundarbans',
  sunderbans: 'sundarbans',
  digha: 'digha',
  murshidabad: 'murshidabad',
  howrah: 'howrah',

  // North-East
  guwahati: 'guwahati',
  gauhati: 'guwahati',
  kaziranga: 'kaziranga',
  majuli: 'majuli',
  tawang: 'tawang',
  bomdila: 'bomdila',
  kohima: 'kohima',
  imphal: 'imphal',
  aizawl: 'aizawl',
  agartala: 'agartala',
  cherrapunji: 'cherrapunji',
  cherapunjee: 'cherrapunji',
  cherrapunjee: 'cherrapunji',
  mawlynnong: 'mawlynnong',
  dawki: 'dawki',
  shillong: 'shillong',
  tezpur: 'tezpur',
  jorhat: 'jorhat',

  // Odisha
  bhubaneswar: 'bhubaneswar',
  bhuvaneshwar: 'bhubaneswar',
  bhubaneshwar: 'bhubaneswar',
  puri: 'puri',
  konark: 'konark',
  cuttack: 'cuttack',
  gopalpur: 'gopalpur',

  // Jharkhand / Bihar / East
  ranchi: 'ranchi',
  jamshedpur: 'jamshedpur',
  netarhat: 'netarhat',
  patna: 'patna',
  gaya: 'gaya',
  bhagalpur: 'bhagalpur',
  deoghar: 'deoghar',

  // Andaman
  andaman: 'andaman',
  'port blair': 'port blair',
  portblair: 'port blair',
  havelock: 'havelock island',
  'havelock island': 'havelock island',
  'neil island': 'neil island',
  baratang: 'baratang',

  // Misc popular getaways
  jibhi: 'jibhi',
};

/** States / regions — wider place search when user names a whole state. */
export const INDIA_REGION_DESTINATIONS = new Set([
  'andhra pradesh',
  'arunachal pradesh',
  'assam',
  'bihar',
  'chhattisgarh',
  'goa',
  'gujarat',
  'haryana',
  'himachal pradesh',
  'himachal',
  'jharkhand',
  'karnataka',
  'kerala',
  'ladakh',
  'madhya pradesh',
  'maharashtra',
  'manipur',
  'meghalaya',
  'mizoram',
  'nagaland',
  'odisha',
  'orissa',
  'punjab',
  'rajasthan',
  'sikkim',
  'tamil nadu',
  'telangana',
  'tripura',
  'uttar pradesh',
  'uttarakhand',
  'west bengal',
  'jammu and kashmir',
  'jammu kashmir',
  'kashmir',
  'andaman',
  'andaman and nicobar',
  'andaman nicobar',
  'delhi',
  'puducherry',
  'pondicherry',
  'chandigarh',
  'lakshadweep',
]);

/** All canonical destination keys (for validation / inference lists). */
export const INDIA_CANONICAL_DESTINATIONS: string[] = [
  ...new Set(Object.values(INDIA_DESTINATION_ALIASES)),
].sort();
